# Site Settings
#
title: Course website
description: A starter template for a course site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io
# baseurl: "" # the subpath of your site, e.g. /blog
# repository: just-the-docs/just-the-docs # for github-metadata

exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md", "disabled"]



# Theme Settings
#
# color_scheme: neu
# search_enabled: true
heading_anchors: true
permalink: pretty

# aux_links:
#  Template Repository: 
#    - https://github.com/just-the-docs/just-the-docs-template
#  Just the Class on GitHub:
#    - 'https://github.com/kevinlin1/just-the-class'



# Collections for website data
collections:
  staffers:
  modules:
  schedules:
#  announcements:

# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      subpath: '/assets/images/'
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

plugins:
  - jekyll-seo-tag